/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Ping */
        get: operations["auth_ping_auth_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_config_get"];
        /** Update Config */
        put: operations["update_config_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cache Stats */
        get: operations["get_cache_stats_config_cache_get"];
        put?: never;
        post?: never;
        /**
         * Clear Cache
         * @description Clear the on-disk translation caches.
         *
         *     `scope=expired` only reaps stale entries; `scope=all` wipes everything
         *     (e.g. when the user changes models). `target` picks which cache:
         *     `paragraph` (default, backward compatible), `pdf` (whole-PDF cache), or
         *     `all` (both). The PDF cache has no TTL, so `scope=expired` doesn't touch it.
         */
        delete: operations["clear_cache_config_cache_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Options */
        get: operations["get_options_config_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Credentials
         * @description Check credentials with the provider.
         *
         *     Whatever the request leaves out comes from the saved settings: the key,
         *     the model, the endpoint. The saved key is only sent to the saved endpoint,
         *     the rule `PUT /config` keeps; checking another endpoint needs the key typed
         *     alongside it.
         */
        post: operations["validate_credentials_config_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdf/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Translated Pdf
         * @description Copy a translated PDF to a permanent, user-chosen location.
         *
         *     The frontend picks `destination_path` with the native Save dialog, so the
         *     user has already agreed to the location (and to overwriting, if the file
         *     exists). All we do here is make a durable copy — everything the pipeline
         *     itself produces lives in a temp dir or an evictable cache.
         *
         *     Runs on a worker thread: a large PDF copy would otherwise stall the event
         *     loop and stutter any in-flight SSE stream.
         */
        post: operations["export_translated_pdf_pdf_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdf/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Pdf */
        get: operations["stream_pdf_pdf_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Ask */
        post: operations["start_ask_rag_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/ask/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Ask Events */
        get: operations["stream_ask_events_rag_ask__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/document/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Forget a document: its record, the paths it was opened from, its chat
         *     indexes and its chat history. Opening the PDF again starts afresh.
         */
        delete: operations["delete_document_rag_document__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/document/{document_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat History
         * @description One document's chat history, oldest first; empty when it has none.
         */
        get: operations["get_chat_history_rag_document__document_id__messages_get"];
        put?: never;
        post?: never;
        /** Clear Chat History */
        delete: operations["clear_chat_history_rag_document__document_id__messages_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description Every recorded document, most recently opened first.
         *
         *     A records query: listing never loads the vector store or the embedding model.
         */
        get: operations["list_documents_rag_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Index */
        post: operations["start_index_rag_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/index/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Index Events */
        get: operations["stream_index_events_rag_index__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Indexes
         * @description Delete every chat index and its chunks: the recovery action for a damaged
         *     vector store (#31).
         *
         *     Documents and chat history stay, and each document is indexed again the
         *     next time chat opens it. An index being built right now is left to finish.
         *     Runs under `_init_lock`, so the store can't open partway through. When it
         *     isn't open, `vectors/` is deleted outright, which works even on a store too
         *     damaged to open.
         */
        post: operations["reset_indexes_rag_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/engine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Setup
         * @description Start an install, or report the one already running.
         *
         *     Never starts a second: two downloads writing the same cache paths is how a
         *     half-written font ends up passing an existence check.
         */
        post: operations["start_setup_setup_engine_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Status */
        get: operations["read_status_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Translation */
        post: operations["start_translation_translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate/prewarm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prewarm */
        post: operations["prewarm_translate_prewarm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Translation */
        post: operations["cancel_translation_translate__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Translation Events */
        get: operations["stream_translation_events_translate__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate/{job_id}/reprioritize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reprioritize Translation
         * @description Update the priority anchor as the user scrolls. Pending chunks closest
         *     to `visible_page` will be picked next. In-flight chunks finish; this is
         *     best-effort. Silently no-ops if the job has already finished.
         */
        post: operations["reprioritize_translation_translate__job_id__reprioritize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * APIKeyMaskedSettings
         * @description Service config with the API key masked. The frontend never sees real keys.
         */
        APIKeyMaskedSettings: {
            /** Base Url */
            base_url?: string | null;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
            /** Has Key */
            has_key: boolean;
            /** Model */
            model: string;
        };
        /** AskProgressPayload */
        AskProgressPayload: {
            /** Message */
            message: string;
            /** Progress */
            progress: number;
        };
        /** AskRequest */
        AskRequest: {
            /** Document Id */
            document_id: string;
            /**
             * Max Pdf Sources
             * @default 5
             */
            max_pdf_sources: number;
            /** Question */
            question: string;
            target_lang?: components["schemas"]["LanguageCode"] | null;
        };
        /**
         * AskResultPayload
         * @description The `answer` and `done` payload for `/rag/ask/{job_id}/events` — the
         *     dict `EnhancedRAGChain.answer_question` returns, verbatim.
         *
         *     Only ever a real answer. A failure ends the stream with `error` instead;
         *     it used to arrive here, as an answer whose text was the error (#31).
         *     `elapsed_seconds` is added by `_run_ask` only for the `done` event, never
         *     for `answer`.
         */
        AskResultPayload: {
            /** Answer */
            answer: string;
            /**
             * Elapsed Seconds
             * @default null
             */
            elapsed_seconds: number | null;
            /** Pdf References */
            pdf_references?: components["schemas"]["PdfReferencePayload"][];
            /**
             * Processing Time
             * @default null
             */
            processing_time: number | null;
            /** Quality Metrics */
            quality_metrics?: {
                [key: string]: number;
            };
            /**
             * Sources Used
             * @default null
             */
            sources_used: {
                [key: string]: number;
            } | null;
            /**
             * Timestamp
             * @default null
             */
            timestamp: string | null;
        };
        /** CacheClearResponse */
        CacheClearResponse: {
            /** Removed */
            removed: number;
            /** Scope */
            scope: string;
        };
        /** CacheStatsResponse */
        CacheStatsResponse: {
            /**
             * Active
             * @default 0
             */
            active: number;
            /** By Service */
            by_service?: {
                [key: string]: number;
            };
            /**
             * Cache Dir
             * @default
             */
            cache_dir: string;
            /**
             * Entries
             * @default 0
             */
            entries: number;
            /**
             * Expired
             * @default 0
             */
            expired: number;
            /**
             * Hit Rate
             * @default 0
             */
            hit_rate: number;
            /**
             * Hits
             * @default 0
             */
            hits: number;
            /**
             * Max Size Mb
             * @default 500
             */
            max_size_mb: number;
            /**
             * Misses
             * @default 0
             */
            misses: number;
            /**
             * Size Mb
             * @default 0
             */
            size_mb: number;
            /**
             * Ttl Days
             * @default 30
             */
            ttl_days: number;
        };
        /**
         * CancelPayload
         * @description The terminal `cancelled` event for `/translate/{job_id}/events`
         *     (`_build_cancel_payload`, `api/routes/translation.py`).
         */
        CancelPayload: {
            /** Original File */
            original_file: string;
            /**
             * Translated File
             * @default null
             */
            translated_file: string | null;
        };
        /** ChatHistoryResponse */
        ChatHistoryResponse: {
            /** Messages */
            messages: components["schemas"]["ChatMessageResponse"][];
        };
        /**
         * ChatMessageResponse
         * @description One saved chat message (#31).
         */
        ChatMessageResponse: {
            answer?: components["schemas"]["AskResultPayload"] | null;
            /** Created At */
            created_at: string;
            /** Id */
            id: number;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Text */
            text: string;
        };
        /**
         * ChunkReadyEventPayload
         * @description `ChunkReadyEvent.to_dict()` — the `chunk_ready` SSE event.
         */
        ChunkReadyEventPayload: {
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /**
             * Cached At
             * @default null
             */
            cached_at: string | null;
            /** Chunk Index */
            chunk_index: number;
            /**
             * Elapsed Seconds
             * @default null
             */
            elapsed_seconds: number | null;
            /**
             * Eta Seconds
             * @default null
             */
            eta_seconds: number | null;
            /** Pages In Chunk */
            pages_in_chunk: [
                number,
                number
            ];
            /**
             * Pages Per Second
             * @default null
             */
            pages_per_second: number | null;
            /** Progress Percent */
            progress_percent: number;
            /** Rolling Pdf Path */
            rolling_pdf_path: string;
            /** Total Chunks */
            total_chunks: number;
            /**
             * Total Pages
             * @default null
             */
            total_pages: number | null;
        };
        /**
         * CompletionEventPayload
         * @description `CompletionEvent.to_dict()` — the terminal `done` payload for
         *     `/translate/{job_id}/events`. Every field is Optional (mirroring the
         *     dataclass's own defaults) because `_run_translation` falls back to
         *     `job.finish("done", {})` if `EventType.FINISH` was never observed.
         */
        CompletionEventPayload: {
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /**
             * Cached At
             * @default null
             */
            cached_at: string | null;
            /**
             * Failed Paragraphs
             * @default 0
             */
            failed_paragraphs: number;
            /**
             * Original File
             * @default null
             */
            original_file: string | null;
            /**
             * Pages Processed
             * @default null
             */
            pages_processed: number | null;
            /**
             * Processing Time Seconds
             * @default null
             */
            processing_time_seconds: number | null;
            /**
             * Retry Count
             * @default 0
             */
            retry_count: number;
            /**
             * Success
             * @default null
             */
            success: boolean | null;
            /**
             * Target Lang
             * @default null
             */
            target_lang: string | null;
            /**
             * Total Paragraphs
             * @default 0
             */
            total_paragraphs: number;
            /**
             * Translated File
             * @default null
             */
            translated_file: string | null;
        };
        /** ConfigResponse */
        ConfigResponse: {
            anthropic: components["schemas"]["APIKeyMaskedSettings"];
            argos: components["schemas"]["APIKeyMaskedSettings"];
            /** Debug Mode */
            debug_mode: boolean;
            gemini: components["schemas"]["APIKeyMaskedSettings"];
            gui: components["schemas"]["GUISettings"];
            openai: components["schemas"]["APIKeyMaskedSettings"];
            processing: components["schemas"]["ProcessingSettings"];
            rag: components["schemas"]["RAGSettings"];
            translation: components["schemas"]["TranslationSettings"];
        };
        /** ConfigUpdateRequest */
        ConfigUpdateRequest: {
            anthropic?: components["schemas"]["EndpointCredentialUpdate"] | null;
            /** Cache Translated Pdfs */
            cache_translated_pdfs?: boolean | null;
            /** Cache Translations */
            cache_translations?: boolean | null;
            default_source_lang?: components["schemas"]["LanguageCode"] | null;
            default_target_lang?: components["schemas"]["LanguageCode"] | null;
            gemini?: components["schemas"]["ServiceCredentialUpdate"] | null;
            /** Max Parallel Chunks */
            max_parallel_chunks?: number | null;
            openai?: components["schemas"]["EndpointCredentialUpdate"] | null;
            preferred_service?: components["schemas"]["TranslationService"] | null;
            /** Rag Enabled */
            rag_enabled?: boolean | null;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentSummaryResponse"][];
        };
        /**
         * DocumentSummaryResponse
         * @description A recorded document, as Settings → Chat lists it (#31). Metadata only.
         */
        DocumentSummaryResponse: {
            /** Chunk Count */
            chunk_count?: number | null;
            /** Display Name */
            display_name: string;
            /** Document Id */
            document_id: string;
            /** Last Opened At */
            last_opened_at: string;
            /** Page Count */
            page_count?: number | null;
            /** Path */
            path?: string | null;
            /** Question Count */
            question_count: number;
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * EmptyPayload
         * @description The terminal `cancelled` event on both RAG streams — `api/routes/rag.py`
         *     sends a literal `{}` for it today.
         */
        EmptyPayload: Record<string, never>;
        /**
         * EndpointCredentialUpdate
         * @description For a service that can talk to another server speaking its API: Ollama,
         *     LM Studio, a proxy (#32).
         *
         *     `base_url=None` leaves the endpoint unchanged and `""` returns to the
         *     provider's own. Changing it while a key is saved needs the key in the same
         *     update, because a saved key is only ever sent to the endpoint it was saved
         *     for (`routes/config.py:update_config`).
         */
        EndpointCredentialUpdate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Model */
            model?: string | null;
        };
        /** EngineAssetGroup */
        EngineAssetGroup: {
            /** Detail */
            detail: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Present */
            present: number;
            /** Ready */
            ready: boolean;
            /** Total */
            total: number;
        };
        /**
         * EngineInstallState
         * @description The install that `POST /setup/engine` starts, as `GET /setup/status`
         *     reports it. Polled rather than streamed — see `api/routes/setup.py`.
         */
        EngineInstallState: {
            /** Error */
            error?: string | null;
            /** Running */
            running: boolean;
            /** Stage */
            stage?: string | null;
        };
        /** EngineStatusResponse */
        EngineStatusResponse: {
            /** Bundled */
            bundled: boolean;
            /** Groups */
            groups: components["schemas"]["EngineAssetGroup"][];
            install: components["schemas"]["EngineInstallState"];
            /** Ready */
            ready: boolean;
        };
        /**
         * ExportPdfRequest
         * @description Save a translated PDF to a permanent location the user picked.
         *
         *     `source_path` is whatever the translation job reported (a rolling file in
         *     the per-job temp dir, or a cache materialization); `destination_path` comes
         *     straight from the native Save dialog.
         */
        ExportPdfRequest: {
            /** Destination Path */
            destination_path: string;
            /** Protect Path */
            protect_path?: string | null;
            /** Source Path */
            source_path: string;
        };
        /** ExportPdfResponse */
        ExportPdfResponse: {
            /** Bytes Written */
            bytes_written: number;
            /** Saved Path */
            saved_path: string;
        };
        /**
         * GUISettings
         * @description GUI-specific settings.
         *
         *     No window geometry here. `tauri-plugin-window-state` persists size,
         *     position and maximized state itself. The `window_width` / `window_height`
         *     fields that used to live here were left over from the PySide6 GUI and
         *     nothing ever read them, so the window opened at `tauri.conf.json`'s
         *     1400×900 every time regardless. Config files that still carry them load
         *     fine — pydantic ignores unknown keys by default.
         */
        GUISettings: {
            /**
             * Auto Preview
             * @description Auto-preview translations
             * @default true
             */
            auto_preview: boolean;
            /**
             * Show Advanced Options
             * @description Show advanced translation options
             * @default false
             */
            show_advanced_options: boolean;
            /**
             * Theme
             * @description UI theme
             * @default system
             * @enum {string}
             */
            theme: "light" | "dark" | "system";
            /**
             * Vietnamese Font Priority
             * @description Prioritize Vietnamese fonts
             * @default true
             */
            vietnamese_font_priority: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
        };
        /** IndexDonePayload */
        IndexDonePayload: {
            /** Cached */
            cached: boolean;
            /** Chunks */
            chunks: number;
            /** Document Id */
            document_id: string;
        };
        /**
         * IndexProgressPayload
         * @description `progress` events from `_run_index`. `chunks` is sent only once there is
         *     a count. `document_id` is on the first event only: the document is named
         *     before the vector store loads, so the chat panel can show its history
         *     meanwhile (#31).
         */
        IndexProgressPayload: {
            /**
             * Chunks
             * @default null
             */
            chunks: number | null;
            /**
             * Document Id
             * @default null
             */
            document_id: string | null;
            /** Progress */
            progress: number;
            /** Stage */
            stage: string;
        };
        /** IndexRequest */
        IndexRequest: {
            /** File Path */
            file_path: string;
        };
        /** JobAccepted */
        JobAccepted: {
            /** Job Id */
            job_id: string;
        };
        /**
         * JobErrorPayload
         * @description The terminal `error` event on all three SSE streams — an uncaught
         *     exception in the job worker, as `{"message": str(exc)}`.
         *
         *     `code` is set only where the client acts on the failure rather than just
         *     showing it: `index_unavailable` from `/rag/ask`, when the document's chat
         *     index had to be cleared and the panel should index it again.
         */
        JobErrorPayload: {
            /**
             * Code
             * @default null
             */
            code: string | null;
            /** Message */
            message: string;
        };
        /**
         * LanguageCode
         * @description Supported language codes with Vietnamese priority.
         * @enum {string}
         */
        LanguageCode: "auto" | "vi" | "en" | "ja" | "zh-cn" | "zh-tw";
        /** LanguageOption */
        LanguageOption: {
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /** OptionsResponse */
        OptionsResponse: {
            /** Languages */
            languages: components["schemas"]["LanguageOption"][];
            /** Services */
            services: components["schemas"]["ServiceOption"][];
        };
        /**
         * ParagraphTranslatedEventPayload
         * @description `ParagraphTranslatedEvent.to_dict()` — the `paragraph_translated` event.
         */
        ParagraphTranslatedEventPayload: {
            /** Paragraphs Seen */
            paragraphs_seen: number;
            /** Service */
            service: string;
            /** Source Preview */
            source_preview: string;
            /** Target Preview */
            target_preview: string;
        };
        /**
         * PdfReferencePayload
         * @description One entry of `AskResultPayload.pdf_references`
         *     (`rag_chain._create_pdf_references`). `page` is 1-indexed, or `None` when
         *     the chunk has no usable page — see `rag_chain._display_page`.
         */
        PdfReferencePayload: {
            /**
             * Bbox
             * @default null
             */
            bbox: number[] | null;
            /** Chunk Id */
            chunk_id: string;
            /** Confidence */
            confidence: number;
            /** Document Id */
            document_id: string;
            /** Document Path */
            document_path: string;
            /**
             * Has Equations
             * @default false
             */
            has_equations: boolean;
            /**
             * Has Figures
             * @default false
             */
            has_figures: boolean;
            /**
             * Has Tables
             * @default false
             */
            has_tables: boolean;
            /**
             * Page
             * @default null
             */
            page: number | null;
            /** Text */
            text: string;
            /**
             * Type
             * @default pdf
             */
            type: string;
        };
        /**
         * PrewarmRequest
         * @description Fire-and-forget request to warm a translator before the user clicks
         *     Translate. For Argos this triggers the en→vi pack install. For LLMs it
         *     instantiates the SDK client so the first translate() call avoids cold-start.
         */
        PrewarmRequest: {
            service?: components["schemas"]["TranslationService"] | null;
            source_lang?: components["schemas"]["LanguageCode"] | null;
            target_lang?: components["schemas"]["LanguageCode"] | null;
        };
        /** PrewarmResponse */
        PrewarmResponse: {
            /** Cached */
            cached: boolean;
            /** Message */
            message: string;
            /** Service */
            service: string;
            /** Warmed */
            warmed: boolean;
        };
        /**
         * ProcessingSettings
         * @description PDF processing settings.
         */
        ProcessingSettings: {
            /**
             * Backup Originals
             * @description Keep backup of original files
             * @default true
             */
            backup_originals: boolean;
            /**
             * Max Parallel Chunks
             * @description BabelDOC sub-jobs in flight at once. 0 = auto (cpu // 2, clamped to 2-8)
             * @default 0
             */
            max_parallel_chunks: number;
            /**
             * Max Workers
             * @description Maximum parallel workers
             * @default 4
             */
            max_workers: number;
            /**
             * Quality Check
             * @description Enable translation quality checks
             * @default true
             */
            quality_check: boolean;
            /**
             * Timeout Seconds
             * @description Processing timeout
             * @default 300
             */
            timeout_seconds: number;
        };
        /**
         * ProgressEventPayload
         * @description `ProgressEvent.to_dict()` — most `progress` SSE events on
         *     `/translate/{job_id}/events`.
         */
        ProgressEventPayload: {
            /** Current Step */
            current_step: number;
            /**
             * Message
             * @default null
             */
            message: string | null;
            /** Progress Percent */
            progress_percent: number;
            /** Stage */
            stage: string;
            /** Total Steps */
            total_steps: number;
        };
        /**
         * RAGSettings
         * @description RAG (Retrieval-Augmented Generation) settings.
         */
        RAGSettings: {
            /**
             * Auto Process Documents
             * @description Auto-process documents for RAG
             * @default true
             */
            auto_process_documents: boolean;
            /**
             * Enabled
             * @description Enable RAG functionality
             * @default false
             */
            enabled: boolean;
        };
        /** ResetIndexesResponse */
        ResetIndexesResponse: {
            /** Removed */
            removed: number;
        };
        /**
         * ServiceCredentialUpdate
         * @description Update payload for one service. `api_key=None` means leave unchanged;
         *     `api_key=""` means clear it. `model` is any name the provider serves, not
         *     only one `/config/options` suggests.
         */
        ServiceCredentialUpdate: {
            /** Api Key */
            api_key?: string | null;
            /** Model */
            model?: string | null;
        };
        /** ServiceOption */
        ServiceOption: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Models */
            models: string[];
            /** Supported Pairs */
            supported_pairs?: string[][] | null;
        };
        /** TranslateRequest */
        TranslateRequest: {
            /**
             * Bypass Cache
             * @description Skip the PDF-level cache lookup for this run (forces a fresh translation)
             * @default false
             */
            bypass_cache: boolean;
            /** File Path */
            file_path: string;
            service?: components["schemas"]["TranslationService"] | null;
            source_lang?: components["schemas"]["LanguageCode"] | null;
            target_lang?: components["schemas"]["LanguageCode"] | null;
            /**
             * Visible Page
             * @description 1-indexed page the viewer is currently showing; seeds the priority queue
             * @default 1
             */
            visible_page: number;
        };
        /**
         * TranslationService
         * @description Supported translation services.
         * @enum {string}
         */
        TranslationService: "openai" | "gemini" | "anthropic" | "argos";
        /**
         * TranslationSettings
         * @description Translation-specific settings.
         */
        TranslationSettings: {
            /**
             * Cache Max Size Mb
             * @description Soft cap for translation cache size (MB)
             * @default 500
             */
            cache_max_size_mb: number;
            /**
             * Cache Translated Pdfs
             * @description Enable PDF-level translation cache (skip re-translating identical PDFs)
             * @default true
             */
            cache_translated_pdfs: boolean;
            /**
             * Cache Translations
             * @description Enable translation caching
             * @default true
             */
            cache_translations: boolean;
            /**
             * Cache Ttl Days
             * @description Days before cached translations expire
             * @default 30
             */
            cache_ttl_days: number;
            /**
             * @description Default source language
             * @default auto
             */
            default_source_lang: components["schemas"]["LanguageCode"];
            /**
             * @description Default target language (Vietnamese priority)
             * @default vi
             */
            default_target_lang: components["schemas"]["LanguageCode"];
            /**
             * Max File Size Mb
             * @description Maximum file size in MB
             * @default 50
             */
            max_file_size_mb: number;
            /**
             * Max Pages
             * @description Maximum pages per PDF
             * @default 50
             */
            max_pages: number;
            /**
             * Min Text Length
             * @description Minimum text length to translate
             * @default 5
             */
            min_text_length: number;
            /**
             * Pdf Cache Max Size Mb
             * @description Soft cap for the translated-PDF cache; oldest entries are LRU-evicted past this
             * @default 1000
             */
            pdf_cache_max_size_mb: number;
            /**
             * @description Preferred translation service
             * @default argos
             */
            preferred_service: components["schemas"]["TranslationService"];
            /**
             * Preserve Formatting
             * @description Preserve PDF formatting
             * @default true
             */
            preserve_formatting: boolean;
        };
        /**
         * ValidateRequest
         * @description What to check against the provider. Whatever is left out comes from the
         *     saved settings, and the saved key is only checked against the saved
         *     endpoint: naming another one needs the key typed alongside it.
         */
        ValidateRequest: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Model */
            model?: string | null;
            service: components["schemas"]["TranslationService"];
        };
        /** ValidateResponse */
        ValidateResponse: {
            /** Message */
            message: string;
            /** Valid */
            valid: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_ping_auth_ping_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_config_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_config_config_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cache_stats_config_cache_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cache_config_cache_delete: {
        parameters: {
            query?: {
                scope?: string;
                target?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheClearResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_options_config_options_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_credentials_config_validate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    export_translated_pdf_pdf_export_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportPdfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportPdfResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_pdf_pdf_file_get: {
        parameters: {
            query: {
                /** @description Absolute path to the PDF */
                path: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_ask_rag_ask_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_ask_events_rag_ask__job_id__events_get: {
        parameters: {
            query?: {
                last_seq?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["AskProgressPayload"] | components["schemas"]["AskResultPayload"] | components["schemas"]["JobErrorPayload"] | components["schemas"]["EmptyPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_rag_document__document_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_history_rag_document__document_id__messages_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_chat_history_rag_document__document_id__messages_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_rag_documents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_index_rag_index_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_index_events_rag_index__job_id__events_get: {
        parameters: {
            query?: {
                last_seq?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["IndexProgressPayload"] | components["schemas"]["IndexDonePayload"] | components["schemas"]["JobErrorPayload"] | components["schemas"]["EmptyPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_indexes_rag_reset_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetIndexesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_setup_setup_engine_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_status_setup_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_translation_translate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prewarm_translate_prewarm_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrewarmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrewarmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_translation_translate__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_translation_events_translate__job_id__events_get: {
        parameters: {
            query?: {
                last_seq?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ProgressEventPayload"] | components["schemas"]["ChunkReadyEventPayload"] | components["schemas"]["ParagraphTranslatedEventPayload"] | components["schemas"]["CompletionEventPayload"] | components["schemas"]["JobErrorPayload"] | components["schemas"]["CancelPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprioritize_translation_translate__job_id__reprioritize_post: {
        parameters: {
            query: {
                visible_page: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
